### ISSUE TITLE
Monatsauswertung Fehler

### ISSUE THREAD

**Issue by mango1402** [SBorg2014/WLAN-Wetterstation#61]
```
2023-04-01 01:03:00.017 - error: javascript.0 (141272) Error in callback: TypeError: VorJahr.substring is not a function
2023-04-01 01:03:00.018 - error: javascript.0 (141272) at VorJahr (script.js.common.Wetterstatistik.Wetterstatistik_V2:428:38)
2023-04-01 01:03:00.018 - error: javascript.0 (141272) at Object.main (script.js.common.Wetterstatistik.Wetterstatistik_V2:157:4)
2023-04-01 01:03:00.018 - error: javascript.0 (141272) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1595:34)
2023-04-01 01:03:00.018 - error: javascript.0 (141272) at Job.invoke (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-schedule/lib/Job.js:171:15)
2023-04-01 01:03:00.018 - error: javascript.0 (141272) at /opt/iobroker/node_modules/iobroker.javascript/node_modules/node-schedule/lib/Invocation.js:268:28
2023-04-01 01:03:00.018 - error: javascript.0 (141272) at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-schedule/lib/Invocation.js:228:7)
2023-04-01 01:03:00.018 - error: javascript.0 (141272) at listOnTimeout (node:internal/timers:559:17)
2023-04-01 01:03:00.018 - error: javascript.0 (141272) at processTimers (node:internal/timers:502:7)

```

Script-Version V2.0.2
Influx: V2

bei den täglichen Auswertungen gab es seit 2.3. keine Probleme....

lg Manfred

**Comment by SBorg2014** [comment]
Sieht nach einem Fehler in deinem April '22 - JSON aus. Der Objekttype ist "string" und die -role "json"?
Alles enthalten (gerade auch *Max_Windboee*, nicht *Max_Windboe* [das musste zur Umstellung durch den Anwender selbst gepatcht werden]):
`[
  {
    "Tiefstwert": -2,
    "Hoechstwert": 25.11,
    "Temp_Durchschnitt": 10,
    "Max_Windboee": 40.39,
    "Max_Regenmenge": 23.9,
    "Regenmenge_Monat": 81.3,
    "warme_Tage": 6,
    "Sommertage": 1,
    "heisse_Tage": 0,
    "Frost_Tage": 4,
    "kalte_Tage": 5,
    "Eistage": 0,
    "sehr_kalte_Tage": 0,
    "Wuestentage": 0,
    "Tropennaechte": 0,
    "Regentage": 0
  }
]`

Erst mit/seit der neuen Version des Skriptes werden auch die aktuellen Daten-JSONs korrekt angelegt.

**Comment by mango1402** [comment]
Aua, das tut jetzt richtig weh.
Wenn der User selbst Datensätze anpassen muss, damit eine abgeänderte Software wieder so funktioniert wie vorher.......

Ist ja schon schlimm genug dass man händisch Datenpunkte umbenennen muss und damit ev. gespeicherte Daten verliert.....
